### ISSUE TITLE
ttyrun-getty@ and serial-getty@ services conflict with each other

### ISSUE THREAD

**Issue by sharkcz** [ibm-s390-linux/s390-tools#105]
Cloning from a downstream bug (https://bugzilla.redhat.com/show_bug.cgi?id=1907781)

Description of problem:
Starting/Enabling `ttyrun-getty@` and `serial-getty@` should be mutually exclusive, since the instance cannot be shared, e.g. `ttyrun-getty@hvc0` and `serial-getty@hv0` cannot connect simultaneously.

I would suggest adding the following stanza to `ttyrun-getty@.service` unit:
````
-------- 8< ---------------- 8< ---------------- 8< ---------------- 8< --------
[Unit]
Conflicts=serial-getty@%i.service
-------- 8< ---------------- 8< ---------------- 8< ---------------- 8< --------
````

How reproducible:
Always

Steps to Reproduce:
1. Start `ttyrun-getty@hvc0`
  `# systemctl start ttyrun-getty@hvc0`

Actual results:
`serial-getty@hvc0` fails

**Comment by hoeppnerj** [comment]
Integrated, thanks for the contribution!
