### ISSUE TITLE
cio_ignore -k does not include '0.0.' prefix

### ISSUE THREAD

**Issue by cohuck** [ibm-s390-linux/s390-tools#114]
Running `cio_ignore -k` to generate a kernel parameter entry omits the `0.0.` prefix and only uses the full bus id for higher subchannel sets. E.g., on one of my systems I get
```
# cio_ignore -k
cio_ignore=all,!0900-0902,!7005,!7105,!7109,!7205,!7305,!0.1.5555
```
This is of course an entirely correct and working kernel parameter, but it looks a bit inconsistent to my eyes, especially as devices are always referenced by the full bus id in sysfs.
Would it make sense to make this more uniform? Or is saving a few characters the idea here?

**Comment by xnox** [comment]
leading zeros are omitted by all s390-tools tooling, udev qeth interface naming. I.e. inputs to lszddev, chzdev etc. Thus it is redundant information.

**Comment by oberpar** [comment]
This behavior is based on a conscious design choice. Given that the s390 kernel command line is limited to ~900 characters and there were already numerous cases where this limit was an issue, saving the character here makes sense.

**Comment by hoeppnerj** [comment]
Closing as per previous comment.
