### ISSUE TITLE
cpi.service sets values in KVM guest and fails

### ISSUE THREAD

**Issue by sharkcz** [ibm-s390-linux/s390-tools#120]
Seems the condition the service (https://github.com/ibm-s390-linux/s390-tools/blob/master/systemd/cpi.service.in#L14) it true even in a KVM guest, but the CPI interface isn't (fully) implemented (?) there and setting the values fail.
````
[root@localhost ~]# journalctl -u cpi
Jul 26 09:28:01 localhost.localdomain systemd[1]: Starting Apply Control Program Identification (CPI)...
Jul 26 09:28:01 localhost.localdomain cpictl[628]: /lib/s390-tools/cpictl: line 112: echo: write error: Operation not supported
Jul 26 09:28:01 localhost.localdomain systemd[1]: cpi.service: Succeeded.
Jul 26 09:28:01 localhost.localdomain systemd[1]: Finished Apply Control Program Identification (CPI).
````

Related: https://bugzilla.redhat.com/show_bug.cgi?id=1985745

**Comment by sharkcz** [comment]
ping :-)

**Comment by mihajlov** [comment]
I would probably be best to suppress the error message in cpictl (cpi_commit), e.g. 
`echo 1 > "$CPI_SET" 2> /dev/null` 
As we will likely implement the CPI interface for KVM in the future, it's OK to enable the service in KVM guests.
