### ISSUE TITLE
cmsfs-fuse fails to mount file systems on Ubuntu 22.04 with error unknown option(s): '-o hard_remove'

### ISSUE THREAD

**Issue by richardflewis** [ibm-s390-linux/s390-tools#131]
cmsfs-fuse fails to mount any cms file system since it forces the hard_remove option and it appears as though that option is no longer recognized by fuse 3.

**Comment by hoeppnerj** [comment]
Hi @richardflewis thanks for the report. Can you please provide details on how to recreate the issue? We'll be looking into it then. Thanks!

**Comment by richardflewis** [comment]
Greetings,

Yes, the recreate is very easy as I cannot yet get it to actually work.  So, I would make a CMS formatted minidisk available to an Ubuntu 22.04 z/VM virtual machine.  Then, I used the following syntax:

cmsfs-fuse -t -o allow_other /dev/disk/by-path/ccw-0.0.0291 /mnt.  The result of this command will be
fuse: unknown option(s): `-o hard_remove'

Similarly: cmsfs-fuse -t /dev/disk/by-path/ccw-0.0.0291 /mnt will result in:
fuse: unknown option(s): `-o hard_remove'

At this point, I cannot find an example of the command that will actually allow the minidisk to be mounted.

Best regards,

Richard Lewis
IBM Washington System Center
z/VM, Linux for IBM Z, KVM for IBM Z

***@***.***

From: Jan Höppner ***@***.***>
Sent: Wednesday, May 4, 2022 3:38 PM
To: ibm-s390-linux/s390-tools ***@***.***>
Cc: Richard Lewis ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-s390-linux/s390-tools] cmsfs-fuse fails to mount file systems on Ubuntu 22.04 with error unknown option(s): '-o hard_remove' (Issue #131)

Hi @richardflewis thanks for the report. Can you please provide details on how to recreate the issue? We'll be looking into it then. Thanks! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Hi @richardflewis<https://github.com/richardflewis> thanks for the report. Can you please provide details on how to recreate the issue? We'll be looking into it then. Thanks!

**Comment by svenschnelle** [comment]
The way how options are handled has changed in fuse3. Will provide a fix.

**Comment by richardflewis** [comment]
Thank you very much!

Best regards,

Richard Lewis
IBM Washington System Center
z/VM, Linux for IBM Z, KVM for IBM Z

***@***.***

From: Sven Schnelle ***@***.***>
Sent: Thursday, May 5, 2022 3:24 AM
To: ibm-s390-linux/s390-tools ***@***.***>
Cc: Richard Lewis ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-s390-linux/s390-tools] cmsfs-fuse fails to mount file systems on Ubuntu 22.04 with error unknown option(s): '-o hard_remove' (Issue #131)

The way how options are handled has changed in fuse3. Will provide a fix. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: <ibm-s390-linux/s390-tools/issues/131/1118248489
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

The way how options are handled has changed in fuse3. Will provide a fix.

**Comment by richardflewis** [comment]
Thank you very much!

Richard Lewis
IBM Washington System Center
z/VM, Linux for IBM Z, KVM for IBM Z

***@***.***

From: Jan Höppner ***@***.***>
Sent: Tuesday, May 10, 2022 7:36 AM
To: ibm-s390-linux/s390-tools ***@***.***>
Cc: Richard Lewis ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [ibm-s390-linux/s390-tools] cmsfs-fuse fails to mount file systems on Ubuntu 22.04 with error unknown option(s): '-o hard_remove' (Issue #131)

Closed #131 via 0981df6. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>> ‍ ‍
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
ZjQcmQRYFpfptBannerEnd

Closed #131<https://github.com/ibm-s390-linux/s390-tools/issues/131> via 0981df6<https://github.com/ibm-s390-linux/s390-tools/commit/0981df62c05e71123bc14483bba347f17aafa59a>.

**Comment by frank-heimes** [comment]
Great - thx Jan, Richard and Sven.
I plan to pick issue [131](https://github.com/ibm-s390-linux/s390-tools/issues/131) with the next (first) s390-tools for jammy SRU ...
