### ISSUE TITLE
add info about the bundled zlib

### ISSUE THREAD

**Issue by sharkcz** [ibm-s390-linux/s390-tools#157]
As s390-tools project is now bundling (part of) zlib, we need to know what version it is and how/if it has been modified to be able to track such information in the distro package. If it is taken from a fork, providing an URL would be also helpful. I assume it's not technically possible to build with a system zlib.

**Comment by mzaslonk** [comment]
Actually there are some words on it in `zipl/include/zlib/zlib.h`. 
Do you think the text should be expanded?

**Comment by sharkcz** [comment]
https://github.com/ibm-s390-linux/s390-tools/blob/master/zipl/include/zlib/zlib.h#L38 mentions 1.1.3, while the current zlib version is 1.2.13, so possibly full of CVEs and bugs. Maybe there could be a new section in https://github.com/ibm-s390-linux/s390-tools/blob/master/README.md#dependencies about the bundled deps.

**Comment by hoeppnerj** [comment]
> https://github.com/ibm-s390-linux/s390-tools/blob/master/zipl/include/zlib/zlib.h#L38 mentions 1.1.3, while the current zlib version is 1.2.13, so possibly full of CVEs and bugs. Maybe there could be a new section in https://github.com/ibm-s390-linux/s390-tools/blob/master/README.md#dependencies about the bundled deps.

Hi Dan, we've discussed it and will likely add the required information to the README.md file (which you suggested, too).
The version used here was taken from the Linux Kernel, which itself saw multiple changes over time. We will mention those details, rationales, and our own changes as well.

And you're right, including zlib like this is a bit tricky in regards to bugs and CVEs. We'll discuss how to handle updates for it.

**Comment by sharkcz** [comment]
Sorry for the late answer, but the proposed text for README looks good to me, it's even more detailed than I would probably do.
